# Generated by Django 4.0.2 on 2022-03-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thisday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time7', models.CharField(max_length=50)),
                ('time8', models.CharField(max_length=50)),
                ('time9', models.CharField(max_length=50)),
                ('time10', models.CharField(max_length=50)),
                ('time11', models.CharField(max_length=50)),
            ],
        ),
    ]
